baseURL = "https://sara-samy.github.io/"
languageCode = "en-us"
title = "Sara Samy"
theme = "bare"

[params]
mainSections = ["posts"]
author = "Sara Samy"
email = "hussein@math.tu-berlin.de"
includeAuthorInTitle = false
disableAttribution = true
# Can be any colour here: https://bulma.io/documentation/layout/hero/#colors
hero_colour = "info"
