baseURL = "https://sara-samy.github.io/"
languageCode = "en-us"
title = "sarasamy.github.io"
theme = ["hugo-tufte", "plausible-hugo"]

[params]
subtitle = "Blog posts"
math = true
hidedate = false
showSummary = false
marginNoteInd = "⊕"
github = "sara-samy"

[params.plausible]
enable = true
debug = false
gitstar = false
outbound_link = true
file_downloads = true
domain = "sara-samy.github.io"
