baseURL = "https://sara-samy.github.io/"
languageCode = "en-us"
title = "Blog posts"
theme = ["hugo-tufte", "plausible-hugo"]

[params]
subtitle = "Fancy subtitle."
math = true
KaTeXVersion = "0.16.4"
KaTeXCDN = "//cdn.jsdelivr.net/npm"
hidedate = false
showSummary = false
marginNoteInd = "⊕"
github = "sara-samy"

[params.plausible]
enable = true
domain = "sara-samy.github.io"
outbound_link = true
file_downloads = true
debug = false
gitstar = false
