baseURL = "https://sara-samy.github.io/"
languageCode = "en-us"
title = "Blog posts"
theme = ["hugo-theme-texify", "plausible-hugo"]

[params]
description = "Personal website using Hugo with TeXify theme"
favicon = "favicon.ico"
customCSS = []
customJS = []
dateFormat = "2006-01-02"
fullTextRSS = true
emphasisWithDots = true
since = "2019"
toc = false

[params.math]
enable = true
use = "katex"

[params.plausible]
enable = true
domain = "sara-samy.github.io"
outbound_link = true
file_downloads = true
debug = false
gitstar = false
