baseURL = "https://sara-samy.github.io/"
languageCode = "en-us"
title = "[SGI] Summer Geometry Initiative - Application"
theme = "bare"

[params]
mainSections = ["posts"]
author = "Sara Samy"
description = "Math student at TU Berlin"
email = "hussein@math.tu-berlin.de"
includeAuthorInTitle = true
disableAttribution = true
# Can be any colour here: https://bulma.io/documentation/layout/hero/#colors
hero_colour = "info"
